# Generated by Django 5.2 on 2026-08-28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plantilla de evaluación",
                "verbose_name_plural": "plantillas de evaluación",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dimensions", to="assessments.assessmenttemplate")),
            ],
            options={
                "verbose_name": "dimensión",
                "verbose_name_plural": "dimensiones",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("question_type", models.CharField(choices=[("SCALE", "Escala de 1 a 10"), ("TEXT", "Respuesta abierta")], db_index=True, default="SCALE", max_length=12)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                ("dimension", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="assessments.dimension")),
            ],
            options={
                "verbose_name": "pregunta",
                "verbose_name_plural": "preguntas",
                "ordering": ("dimension__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("DRAFT", "Borrador"), ("IN_PROGRESS", "En progreso"), ("COMPLETED", "Completada")], db_index=True, default="DRAFT", max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_assessments", to=settings.AUTH_USER_MODEL)),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assessments", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assessments", to="assessments.assessmenttemplate")),
            ],
            options={
                "verbose_name": "evaluación",
                "verbose_name_plural": "evaluaciones",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="assessments.assessment")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="answers", to="assessments.question")),
            ],
            options={
                "verbose_name": "respuesta",
                "verbose_name_plural": "respuestas",
            },
        ),
        migrations.AddConstraint(
            model_name="dimension",
            constraint=models.UniqueConstraint(fields=("template", "slug"), name="assessment_dimension_template_slug_unique"),
        ),
        migrations.AddConstraint(
            model_name="dimension",
            constraint=models.UniqueConstraint(fields=("template", "order"), name="assessment_dimension_template_order_unique"),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(fields=("dimension", "order"), name="assessment_question_dimension_order_unique"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["participant", "status"], name="assess_part_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(fields=("assessment", "question"), name="assessment_answer_assessment_question_unique"),
        ),
    ]
